AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  napa:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::753264724061:role/service-role/napa-role-m5r63jtj'
      Layers:
        - 'arn:aws:lambda:us-east-1:753264724061:layer:requests-pdf:1'
